### ISSUE TITLE
create scenes/actions request

### ISSUE THREAD

**Issue by lmn451** [qoomon/smart-life-webapp#101]
Is the an option to add creating scenes / configure actions?

**Comment by qoomon** [comment]
If you add a `#`to the end of your automation names, those will then be then displayed and can be triggered. This is needed because the api is somehow broken and does not distinguish between scenes and automations both have the type `scene`
see https://github.com/qoomon/smart-life-webapp/blob/1b29dc361a4dc54f839efc3117af070f877baa0f/src/libs/tuya.js#L101
